### ISSUE TITLE
Meeting 5

### ISSUE THREAD

**Issue by yolophg** [VocaMastery/voca-mastery#27]
## 1. Check Done of issue
- [x] https://github.com/VocaMastery/voca-mastery/issues/15
- [x] https://github.com/VocaMastery/voca-mastery/issues/16
- [x] https://github.com/VocaMastery/voca-mastery/issues/18
- [x] https://github.com/VocaMastery/voca-mastery/issues/19
- [x] https://github.com/VocaMastery/voca-mastery/issues/14
- [x] https://github.com/VocaMastery/voca-mastery/issues/24

## 2. To-do for next week
- https://github.com/VocaMastery/voca-mastery/issues/13
- https://github.com/VocaMastery/voca-mastery/issues/8
- https://github.com/VocaMastery/voca-mastery/issues/10
